apiVersion: v1
kind: Service
metadata:
  name: mqttutility-service
  namespace: utility
spec:
  selector:
    app: mqttutility-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 31002
  type: NodePort
