apiVersion: v1
kind: Service
metadata:
  name: edge-service
  namespace: edge
spec:
  selector:
    app: edge-app
  ports:
    - protocol: "TCP"
      port: 9090
      targetPort: 8080
      nodePort: 31000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-app
  namespace: edge
spec:
  selector:
    matchLabels:
      app: edge-app
  replicas: 2
  template:
    metadata:
      labels:
        app: edge-app
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: kubernetes.io/hostname
#                    operator: In
#                    values:
#                      - edgenode-pi
#                      - edgenode-ubuntu
      containers:
        - name: edge-app
          image: savantripathi22/edge:aug19
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
      nodeSelector:
          kubernetes.io/hostname: edgenode-pi
      tolerations:
        - key: "node-role.kubernetes.io/edge"
          operator: "Exists"
          effect: "NoSchedule"
