apiVersion: v1
kind: Service
metadata:
  name: staging-edge-service
  namespace: staging
spec:
  selector:
    app: staging-edge-app
  ports:
    - protocol: "TCP"
      port: 9090
      targetPort: 8080
      nodePort: 32000
  type: NodePort
