apiVersion: v1
kind: Service
metadata:
  name: bacnetutility-service
  namespace: utility
spec:
  selector:
    app: bacnetutility-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 31001
  type: NodePort
