
apiVersion: v1
kind: Service
metadata:
  name: staging-opcuautility-service
  namespace: staging
spec:
  selector:
    app: staging-opcuautility-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 32003
  type: NodePort
