apiVersion: v1
kind: Service
metadata:
  name: tag-v2-service
  namespace: terrestrialplatform-v2
spec:
  selector:
    app: tag-v2-app
  ports:
    - protocol: "TCP"
      port: 8044
      targetPort: 8080
  type: ClusterIP
