apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-homepage-app
  namespace: website-homepage
spec:
  selector:
    matchLabels:
      app: website-homepage-app
  replicas: 1
  template:
    metadata:
      labels:
        app: website-homepage-app
    spec:
      containers:
        - name: website-homepage-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
