apiVersion: v1
kind: Service
metadata:
  name: staging-mqttutility-service
  namespace: staging
spec:
  selector:
    app: staging-mqttutility-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 32002
  type: NodePort
