apiVersion: networking.k8s.io/v1 
kind: Ingress  
metadata:  
  name: staging-bacnetutility-ingress 
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/service-upstream: "true"

spec:
  ingressClassName: nginx
  rules:
    - host: platform.tpcloud.tech
      http:
        paths:
          - path: /bacnetutility/(.*)
            pathType: Prefix
   
            backend:
   
              service:
   
                name: staging-bacnetutility-service
   
                port:
   
                  number: 32001
  
