apiVersion: v1
kind: Service
metadata:
  name: staging-bacnetutility-service
  namespace: staging
spec:
  selector:
    app: staging-bacnetutility-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 32001
  type: NodePort
