
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-v2-app
  namespace: terrestrialplatform-v2
spec:
  selector:
    matchLabels:
      app: auth-v2-app
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-v2-app
    spec:
      containers:
        - name: auth-v2-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8011
