apiVersion: v1
kind: Service
metadata:
  name: auth-v2-svc
  # namespace: terrestrial-platform
spec:
  selector:
    app: auth-v2-app
  ports:
    - protocol: "TCP"
      port: 8011
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-v2-app
spec:
  selector:
    matchLabels:
      app: auth-v2-app
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-v2-app
    spec:
      containers:
        - name: auth-v2-app
          image: savantripathi22/auth_v2:june5
          imagePullPolicy: Always
          ports:
            - containerPort: 8011
