apiVersion: v1
kind: Service
metadata:
  name: alarm-v2-svc
  # namespace: terrestrial-platform
spec:
  selector:
    app: alarm-v2-app
  ports:
    - protocol: "TCP"
      port: 8033
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-v2-app
spec:
  selector:
    matchLabels:
      app: alarm-v2-app
  replicas: 1
  template:
    metadata:
      labels:
        app: alarm-v2-app
    spec:
      containers:
        - name: alarm-v2-app
          image: savantripathi22/alarm_v2:july10
          imagePullPolicy: Always
          ports:
            - containerPort: 8033
