apiVersion: v1
kind: Service
metadata:
  name: history-v2-svc
  # namespace: terrestrial-platform
spec:
  selector:
    app: history-v2-app
  ports:
    - protocol: "TCP"
      port: 8055
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-v2-app
spec:
  selector:
    matchLabels:
      app: history-v2-app
  replicas: 1
  template:
    metadata:
      labels:
        app: history-v2-app
    spec:
      containers:
        - name: history-v2-app
          image: savantripathi22/history_v2:june15
          imagePullPolicy: Always
          ports:
            - containerPort: 8055
