
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: staging-master-app
  namespace: staging
spec:
  selector:
    matchLabels:
      app: staging-master-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: staging-master-app
    spec:
      containers:
        - name: staging-master-app 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8088