
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: master-app
  namespace: terrestrialplatform-v2
spec:
  selector:
    matchLabels:
      app: master-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: master-app
    spec:
      containers:
        - name: master-app 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8088