apiVersion: v1
kind: Service
metadata:
  name: rtuutility-service
  namespace: utility
spec:
  selector:
    app: rtuutility-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 31005
  type: NodePort



# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "rtuutility.fullname" . }}
#   labels:
#     {{- include "rtuutility.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "rtuutility.selectorLabels" . | nindent 4 }}
